# Air configuration for test watching
root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  bin = ""
  cmd = "make fast-check"
  delay = 1000
  exclude_dir = ["assets", "vendor", "testdata", "build"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["Makefile"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
